import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Navbar } from "@/components/layout/Navbar";
import {
  Brain,
  Zap,
  Layers,
  MessageCircle,
  Trophy,
  Coins,
  ArrowRight,
  Sparkles,
  Users,
  Target,
  Star,
} from "lucide-react";

export default function Landing() {
  const features = [
    {
      icon: <Brain className="h-6 w-6" />,
      title: "AI-Powered Learning",
      description: "Personalized questions generated by Gemini 2.0 for your exact syllabus",
    },
    {
      icon: <Zap className="h-6 w-6" />,
      title: "Adaptive Quizzes",
      description: "Difficulty adjusts in real-time based on your performance",
    },
    {
      icon: <Layers className="h-6 w-6" />,
      title: "Smart Flash Cards",
      description: "Spaced repetition system to maximize retention",
    },
    {
      icon: <MessageCircle className="h-6 w-6" />,
      title: "AI Tutor",
      description: "Get instant help from an AI tutor that explains concepts simply",
    },
  ];

  const stats = [
    { value: "50,000+", label: "Students" },
    { value: "1M+", label: "Questions Solved" },
    { value: "4.9/5", label: "Rating" },
    { value: "98%", label: "Success Rate" },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 overflow-hidden">
        {/* Background effects */}
        <div className="absolute inset-0 bg-hero-pattern" />
        <div className="absolute top-1/4 left-1/4 h-96 w-96 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 h-96 w-96 rounded-full bg-accent/10 blur-3xl" />

        <div className="container relative mx-auto px-4">
          <div className="mx-auto max-w-4xl text-center">
            {/* Badge */}
            <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-2 text-sm">
              <Sparkles className="h-4 w-4 text-primary" />
              <span>Powered by AI • Built for Commerce Students</span>
            </div>

            {/* Headline */}
            <h1 className="mb-6 font-display text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
              Master Commerce{" "}
              <span className="gradient-text">Like a Champion</span>
            </h1>

            <p className="mx-auto mb-8 max-w-2xl text-lg text-muted-foreground sm:text-xl">
              The ultimate AI-powered learning platform for Class 11 & 12 Commerce students.
              Personalized practice, instant feedback, and gamified learning.
            </p>

            {/* CTA Buttons */}
            <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Link to="/auth/register">
                <Button variant="hero" size="xl" className="group">
                  Start Learning Free
                  <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
                </Button>
              </Link>
              <Link to="/auth/login">
                <Button variant="outline" size="xl">
                  I have an account
                </Button>
              </Link>
            </div>

            {/* Welcome bonus */}
            <div className="mt-8 inline-flex items-center gap-2 text-sm text-muted-foreground">
              <div className="coin-badge !py-1 !text-xs">
                <Coins className="h-3 w-3" />
                100
              </div>
              <span>Free coins on signup • No credit card required</span>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="border-y border-border/50 bg-card/50 py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <p className="font-display text-3xl font-bold gradient-text sm:text-4xl">
                  {stat.value}
                </p>
                <p className="mt-1 text-sm text-muted-foreground">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="font-display text-3xl font-bold sm:text-4xl">
              Everything You Need to{" "}
              <span className="gradient-text">Ace Your Exams</span>
            </h2>
            <p className="mt-4 text-muted-foreground">
              Multiple learning modes designed for how you actually learn best
            </p>
          </div>

          <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, index) => (
              <div
                key={feature.title}
                className="arcade-card animate-slide-up"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="relative z-10">
                  <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-accent text-white">
                    {feature.icon}
                  </div>
                  <h3 className="mb-2 font-display text-lg font-semibold">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Subjects Section */}
      <section className="py-20 bg-card/30">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-2xl text-center mb-12">
            <h2 className="font-display text-3xl font-bold sm:text-4xl">
              Complete <span className="gradient-text">CBSE Commerce</span> Coverage
            </h2>
            <p className="mt-4 text-muted-foreground">
              All subjects, all chapters, aligned with your syllabus
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {["Accountancy", "Business Studies", "Economics", "Mathematics"].map((subject) => (
              <div key={subject} className="arcade-card !p-4 text-center">
                <div className="relative z-10">
                  <Target className="mx-auto mb-3 h-8 w-8 text-primary" />
                  <h3 className="font-display font-semibold">{subject}</h3>
                  <p className="mt-1 text-xs text-muted-foreground">Class 11 & 12</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="arcade-card mx-auto max-w-3xl !p-8 text-center sm:!p-12">
            <div className="relative z-10">
              <Trophy className="mx-auto mb-6 h-16 w-16 text-gold" />
              <h2 className="font-display text-3xl font-bold sm:text-4xl">
                Ready to Become a <span className="gradient-text">Champion</span>?
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
                Join thousands of Commerce students who are acing their exams with
                AI-powered personalized learning.
              </p>
              <div className="mt-8">
                <Link to="/auth/register">
                  <Button variant="hero" size="xl" className="group">
                    Start Your Journey
                    <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-primary to-accent">
                <span className="font-display text-sm font-bold text-white">C</span>
              </div>
              <span className="font-display font-semibold">ChampionsPrep</span>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2025 ChampionsPrep. Made with ❤️ for Indian Students.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
